# Generated by Django 3.1.4 on 2021-08-21 17:57

from django.db import migrations, models
import django.db.models.deletion
import transactions.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('description', models.CharField(max_length=120)),
                ('nature', models.IntegerField(choices=[(1, 'Entrada'), (2, 'Saída')])),
                ('signal', models.IntegerField(choices=[(1, '+'), (2, '-')])),
            ],
            options={
                'verbose_name': 'Transaction type',
                'verbose_name_plural': 'Transactions types',
                'db_table': 'transaction_type',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, validators=[transactions.validator.validaCpf])),
                ('value', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('card', models.CharField(max_length=120)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='store.stores')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.transactiontype')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transaction',
                'ordering': ['date'],
            },
        ),
    ]
