# Generated by Django 3.1.4 on 2021-08-22 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210822_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactiontype',
            options={'ordering': ['type_transactions'], 'verbose_name': 'Transaction type', 'verbose_name_plural': 'Transactions types'},
        ),
        migrations.RenameField(
            model_name='transactiontype',
            old_name='type',
            new_name='type_transactions',
        ),
    ]
