# Generated by Django 3.1.4 on 2021-08-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20210822_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.FloatField(),
        ),
    ]
